---
# Site settings
title: Adrian Moisey
header-img: img/home-bg.jpg
email: adrian@changeover.za.net
copyright_name: Adrian Moisey
description: "My personal notes and blog"
baseurl: ""
url: "http://adrianmoisey.github.io"
twitter_username: adrianmoisey
github_username: adrianmoisey
facebook_username:
email_username: myblog@changeover.za.net
getpocket_id: "@fu6g3d56pr5eDA2776T280gT02Acpd04eW6HnRAaN2m393y1962cpha4o15Zh0Vq"

# Google Analytics
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less", "node_modules", "Gruntfile.js", "package.json", "README.md"]

gems: [jekyll-paginate, jekyll-feed]
